---
name: 'Ansible Galaxy Role Importer'
description: 'Github Action for import your role into Ansible Galaxy.'

inputs:
  api_key:
    description: 'Ansible Galaxy API Key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    action_api_key: ${{ inputs.api_key }}

branding:
  icon: 'book'  
  color: 'gray-dark'
